.TH KCM-TABLET "1" "2010-01-03" "kcm-tablet - kcm module that implements a GUI for the Wacom Linux Drivers" 
.SH NAME
kcm-tablet \- kcm module that implements a GUI for the Wacom Linux Drivers.

.SH SYNOPSIS
.B kcm-tablet

.SH DESCRIPTION

.B kcm-tablet
KDE 4 KCModule

This module implements a GUI for the Wacom Linux Drivers and extends it
with profile support to handle different button / pen layouts per profile.

For hardware support have a look at http://www.linuxwacom.sourceforge.net

All tablets can be set up as long as they are found via xorg.conf or HAL configuration.

.SH AUTHOR
.B kcm-tablet
is developed by Jörg Ehrichs

This manual page was written by Lisandro Damián Nicanor Pérez Meyer for
the Debian project, but may be used by others.
